version: '3.7'
services:
  app:
    build: .
    volumes:
      - ./:/home/node/api
    working_dir: /home/node/api
    command: npm start
    depends_on:
      - dbpostgres
    ports:
      - '4050:4050'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://pguser:pguser@dbpostgres/dbdev
      PORT: 4050
  dbpostgres:
    image: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: dbdev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
